name: FitnesApp
options:
  bundleIdPrefix: com.ilich
  deploymentTarget:
    iOS: "18.6"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.2"
    SWIFT_STRICT_CONCURRENCY: complete
    SWIFT_APPROACHABLE_CONCURRENCY: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
    DEVELOPMENT_TEAM: ""
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  FitnesApp:
    type: application
    platform: iOS
    sources:
      - path: FitnesApp
        excludes:
          - "Tests/**"
    resources:
      - FitnesApp/Resources
    info:
      path: FitnesApp/Resources/Info.plist
      properties:
        UIUserInterfaceStyle: Dark
        UILaunchScreen: {}
        NSUserNotificationsUsageDescription: "Уведомление об окончании таймера отдыха"
        UIAppFonts:
          - SpaceGrotesk-Bold.ttf
          - SpaceGrotesk-Medium.ttf

  FitnesAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FitnesApp/Tests
    dependencies:
      - target: FitnesApp
